# Cvičení 1: Pokročilé úpravy - spojování

In [31]:
import pandas as pd

# Příprava vstupního DataFramu
food_nutrient = pd.read_csv("food_nutrient.csv")
food_sample_100 = pd.read_csv("food_sample_100.csv")
food_other = pd.read_csv("food_other.csv")
food = pd.concat([food_sample_100, food_other], ignore_index=True)
food_merged = pd.merge(food, food_nutrient, on="fdc_id")

## Značky a výrobci

Stáhni si data z
tabulky [branded_food.csv](https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/spojovani/excs/znacky/branded_food.csv),
která obsahuje data o konkrétních potravinách od výrobců. Tabulku načti do `pandas` tabulky `branded_food`.

In [32]:
branded_food = pd.read_csv("branded_food.csv")
branded_food.shape

(9541, 20)

Pro tabulku `branded_food` splň následující úkoly.

- Zobraz si prvních několik řádků tabulky a podívej se na to, jaké jsou v ní sloupce a jaké jsou v nich hodnoty.
- Ve sloupci `brand_owner` jsou názvy výrobců potravin. Zjisti tři výrobce s největším počtem potravin v tabulce.
- Ve sloupci `branded_food_category` jsou kategorie potravin. Zjisti pět kategorií s největších počtem potravin v
  tabulce.

Nápověda: Na body 2 a 3 využij metodu, kterou jsme si již ukazovali v předchozí lekci. Její název se skládá ze dvou
slov - anglického výrazu pro hodnotu a pro počet.

In [33]:
branded_food.head(3)

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
0,1106032,BRAKEBUSH BROTHERS INC.,NaN,NaN,10038034720202,INGREDIENTS: BONELESS CHICKEN BREAST MEAT WITH...,NaN,85.0,g,NaN,Meat/Poultry/Other Animals Prepared/Processed,GDSN,NaN,2020-09-03,2020-11-13,United States,NaN,NaN,NaN,NaN
1,1107191,Mahco Inc,NaN,NaN,877448001674,"TOMATO PUREE (TOMATOES), CARROTS, ONIONS, SUN-...",NaN,125.0,g,NaN,Prepared Pasta & Pizza Sauces,LI,NaN,2020-09-22,2020-11-13,United States,NaN,NaN,NaN,NaN
2,1107295,Hormel Foods Corporation,NaN,NaN,37600665605,MASA FLOUR (GROUND WHITE CORN WITH A TRACE OF ...,NaN,30.0,g,NaN,"Chips, Pretzels & Snacks",LI,NaN,2020-04-08,2020-11-13,United States,NaN,NaN,NaN,NaN

In [34]:
branded_food["brand_owner"].value_counts().head(3)

brand_owner
Wal-Mart Stores, Inc.    219
Target Stores            199
Meijer, Inc.             168
Name: count, dtype: int64

In [35]:
branded_food["branded_food_category"].value_counts().head(5)

branded_food_category
Popcorn, Peanuts, Seeds & Related Snacks    504
Candy                                       415
Cheese                                      405
Ice Cream & Frozen Yogurt                   310
Cookies & Biscuits                          272
Name: count, dtype: int64

V tabulce je sloupec `fdc_id`, pomocí kterého ji můžeš propojit s tabulkou `food_merged`. Protože názvy jsou v obou
tabulkách stejné, takže by bylo možné použít parametr `on`. Vyzkoušej si ale místo toho parametry `left_on`
a `right_on`, kterým dáš stejnou hodnotu, tj. název sloupce `fdc_id`. Výsledek ulož do tabulky `food_merged_brands`.

In [36]:
food_merged_brands = pd.merge(food_merged, branded_food, left_on="fdc_id", right_on="fdc_id")
# ... pokud nevyplníme parametr "how", použije se výchozí hodnota inner

food_merged_brands.head()

,fdc_id,data_type,description,food_category_id,publication_date,nutrient_id,amount,data_points,derivation_id,min,...,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
0,1106032,branded_food,"Chicken, FC Beer Battered Boneless Wing Fritte...",NaN,2020-11-13,1257,NaN,NaN,71.0,NaN,...,Meat/Poultry/Other Animals Prepared/Processed,GDSN,NaN,2020-09-03,2020-11-13,United States,NaN,NaN,NaN,NaN
1,1106032,branded_food,"Chicken, FC Beer Battered Boneless Wing Fritte...",NaN,2020-11-13,1253,24.00,NaN,71.0,NaN,...,Meat/Poultry/Other Animals Prepared/Processed,GDSN,NaN,2020-09-03,2020-11-13,United States,NaN,NaN,NaN,NaN
2,1106032,branded_food,"Chicken, FC Beer Battered Boneless Wing Fritte...",NaN,2020-11-13,1008,141.00,NaN,71.0,NaN,...,Meat/Poultry/Other Animals Prepared/Processed,GDSN,NaN,2020-09-03,2020-11-13,United States,NaN,NaN,NaN,NaN
3,1106032,branded_food,"Chicken, FC Beer Battered Boneless Wing Fritte...",NaN,2020-11-13,1089,1.18,NaN,71.0,NaN,...,Meat/Poultry/Other Animals Prepared/Processed,GDSN,NaN,2020-09-03,2020-11-13,United States,NaN,NaN,NaN,NaN
4,1106032,branded_food,"Chicken, FC Beer Battered Boneless Wing Fritte...",NaN,2020-11-13,1162,0.00,NaN,75.0,NaN,...,Meat/Poultry/Other Animals Prepared/Processed,GDSN,NaN,2020-09-03,2020-11-13,United States,NaN,NaN,NaN,NaN

Pro tabulku `food_merged_brands` splň následující úkoly.

- U výsledné tabulky `food_merged_brands` zkontroluj počet řádků a srovnej ho s původní tabulkou `food_merged`. Ubyly
  nějaké řádky? A čím to je?
- Nyní proveď operaci `merge` znovu, ale s parametrem `how` nastaveným na hodnotu `left`. Zkontroluj počet řádků a
  porovnej ho s počtem řádků tabulky `food_merged_brands`. Proč se počet liší?

In [37]:
print(f"Shape branded_food: {branded_food.shape}")
print(f"Shape food_merged: {food_merged.shape}")

Shape branded_food: (9541, 20)
Shape food_merged: (135336, 17)

In [38]:
food_merged_brands_left = pd.merge(food_merged, branded_food, left_on="fdc_id", right_on="fdc_id", how="left")
food_merged_brands_left

,fdc_id,data_type,description,food_category_id,publication_date,nutrient_id,amount,data_points,derivation_id,min,...,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
0,2644829,sub_sample_food,"lentils, dry",16.0,2023-10-19,1101,1.58,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2347263,sub_sample_food,heavy cream,1.0,2022-10-28,1258,20.00,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2261954,sub_sample_food,"Flour, potato",11.0,2022-04-28,1102,21.80,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01,1051,0.69,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01,1007,98.40,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135331,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1005,4.07,NaN,70.0,NaN,...,Tomatoes,LI,14.5 oz/411 g,2023-09-20,2023-10-26,United States,NaN,NaN,NaN,NaN
135332,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1004,0.41,NaN,70.0,NaN,...,Tomatoes,LI,14.5 oz/411 g,2023-09-20,2023-10-26,United States,NaN,NaN,NaN,NaN
135333,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1003,0.81,NaN,70.0,NaN,...,Tomatoes,LI,14.5 oz/411 g,2023-09-20,2023-10-26,United States,NaN,NaN,NaN,NaN
135334,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1235,0.00,NaN,70.0,NaN,...,Tomatoes,LI,14.5 oz/411 g,2023-09-20,2023-10-26,United States,NaN,NaN,NaN,NaN
135335,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1114,0.00,NaN,70.0,NaN,...,Tomatoes,LI,14.5 oz/411 g,2023-09-20,2023-10-26,United States,NaN,NaN,NaN,NaN

In [39]:
print(f"Shape branded_food: {branded_food.shape}")
print(f"Shape food_merged: {food_merged.shape}")
print(f"Shape food_merged_brands (inner merge): {food_merged_brands.shape}")
print(f"Shape food_merged_brands_left (left merge): {food_merged_brands_left.shape}")

Shape branded_food: (9541, 20)
Shape food_merged: (135336, 17)
Shape food_merged_brands (inner merge): (129284, 36)
Shape food_merged_brands_left (left merge): (135336, 36)

**...Proč se počet liší?**
- `food_merged_brands` spojeno výchozí metodou `inner`
    - -> výsledek obsahuje pouze záznamy (řádky), pro které se `fdc_id` shoduje v obou vstupních tabulkách (průnik). Tím pádem výsledek obsahuje jen záznamy, které mají jak informace o potravině (DF food_merged), tak informace o značce (DF branded_food).
    
- `food_merged_brands_left` spojeno metodou `left`
    - -> výsledek obsahuje záznamy (řádky), pro které se `fdc_id` shoduje v obou vstupních tabulkách plus všechny ostatní záznamy (řádky) z levé (první) vstupní tabulky; záznamy z levé tabulky, pro které nebyl nalezen záznam v pravé tabulce, budou zprava doplněny sloupci s prázdnými hodnotami (NaN). Konkrétně jde o potraviny (DF food_merged), ke kterým nebyly nalezeny informace o značce (DF branded_food).

- ... Nicméně zrovna v tomto příkladu se počty neliší, jelikož při využití obou metod jsou úspěšně spárovány všechny záznamy z levé tabulky.